/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ht.sys.sysgesbricolocal.vue;

import ht.sys.sysgesbricolocal.main.SysGestBricoLocalClient;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import javax.swing.JOptionPane;

/**
 *
 * @author Rose
 */
public class FrmAdresseServeurApplication extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdresseServeurApplication
     */
    public FrmAdresseServeurApplication() {
        initComponents();
        initComponents();
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.getImage("C:/papa/bricopied.JPG");
        setIconImage(img);
    }

    /**
     * 127.0.0.1=9 129.123.123.123=15 This method is called from within the
     * constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panCorpsConnexion = new javax.swing.JPanel();
        panConnexion = new javax.swing.JPanel();
        txtAdresseServeur = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        lblPied = new javax.swing.JLabel();
        btnQuitterConnexion1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Systeme de gestion Brico Local");
        setResizable(false);

        panCorpsConnexion.setBackground(new java.awt.Color(255, 204, 0));
        panCorpsConnexion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        panConnexion.setBackground(new java.awt.Color(255, 255, 255));

        txtAdresseServeur.setToolTipText("Exemple: 192.168.100.1");
        txtAdresseServeur.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtAdresseServeurCaretUpdate(evt);
            }
        });

        jLabel2.setText("Saisir adresse du serveur d'application");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblMessage.setText("|");

        lblPied.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ht/sys/sysgesbricolocal/img/piedConnexion.jpg"))); // NOI18N

        btnQuitterConnexion1.setBackground(new java.awt.Color(204, 204, 204));
        btnQuitterConnexion1.setText("Configurer");
        btnQuitterConnexion1.setBorder(null);
        btnQuitterConnexion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterConnexion1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panConnexionLayout = new javax.swing.GroupLayout(panConnexion);
        panConnexion.setLayout(panConnexionLayout);
        panConnexionLayout.setHorizontalGroup(
            panConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConnexionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPied, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAdresseServeur)
                    .addComponent(btnQuitterConnexion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panConnexionLayout.setVerticalGroup(
            panConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConnexionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAdresseServeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuitterConnexion1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPied)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panCorpsConnexionLayout = new javax.swing.GroupLayout(panCorpsConnexion);
        panCorpsConnexion.setLayout(panCorpsConnexionLayout);
        panCorpsConnexionLayout.setHorizontalGroup(
            panCorpsConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCorpsConnexionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panCorpsConnexionLayout.setVerticalGroup(
            panCorpsConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCorpsConnexionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panCorpsConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panCorpsConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitterConnexion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterConnexion1ActionPerformed
        // TODO add your handling code here:
        
        if (txtAdresseServeur.getText().equals("")) {
            lblMessage.setForeground(Color.red);
            lblMessage.setText("Adresse IP Incorrect");
        } 
           
            int i = JOptionPane.showConfirmDialog(null, "Voulez-vous configurer l'adresse IP du serveur d'application?", "Confirmer Configuration", 2);
            if (i == 0) {
                SysGestBricoLocalClient.adrc = txtAdresseServeur.getText().trim();
                try {
                    JOptionPane.showMessageDialog(null, "Prob..."+SysGestBricoLocalClient.adr);
                    SysGestBricoLocalClient.ObjectExp();
                     JOptionPane.showMessageDialog(null, "Prob..."+SysGestBricoLocalClient.adr);
                    this.dispose();
                    SysGestBricoLocalClient.demarrer();
                } catch (NamingException ex) {
                    Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                
            }
        }
    }//GEN-LAST:event_btnQuitterConnexion1ActionPerformed

    private void txtAdresseServeurCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtAdresseServeurCaretUpdate
        // TODO add your handling code here:
//        if (txtAdresseServeur.getText().equals("") || (txtAdresseServeur.getText().length() <9 || txtAdresseServeur.getText().length() >15)) {
//            lblMessage.setForeground(Color.red);
//            lblMessage.setText("Adresse IP Incorrect");
//            //JOptionPane.showMessageDialog(null, "Prob...");
//        } else {
//        lblMessage.setForeground(Color.blue);
//            lblMessage.setText("");
//        }
    }//GEN-LAST:event_txtAdresseServeurCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdresseServeurApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdresseServeurApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdresseServeurApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdresseServeurApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmAdresseServeurApplication().setVisible(true);
//            }
//        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuitterConnexion1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPied;
    private javax.swing.JPanel panConnexion;
    private javax.swing.JPanel panCorpsConnexion;
    public static javax.swing.JTextField txtAdresseServeur;
    // End of variables declaration//GEN-END:variables
}
